<?php

namespace App\Tests\Application\Controller;

use App\Domain\Sport\SportEntity;
use App\Domain\Sport\SportRepositoryInterface;
use App\Tests\Application\ApplicationTestCase;

class MatchControllerTest extends ApplicationTestCase
{
    private readonly SportEntity $sportEntity;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $sportRepository = $this->getContainer()->get(SportRepositoryInterface::class);
        $this->sportEntity = new SportEntity(
            $sportRepository->generateId(),
            'Test Sport',
            ''
        );
        $sportRepository->store($this->sportEntity);
    }

    public function testCreateAndStore(): void
    {
        $initialResponse = $this->client->request('GET', $this->router->generate('match.create'));
        $this->assertResponseStatusCodeSame(200);
    }

}
