<?php

namespace App\Tests\Application;

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\DomCrawler\Crawler;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * @internal
 *
 * @coversNothing
 */
class ApplicationTestCase extends WebTestCase
{
    protected readonly KernelBrowser $client;
    protected readonly UrlGeneratorInterface $router;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = self::createClient();
        $this->router = $this->getContainer()->get(UrlGeneratorInterface::class);
    }

    protected function doFormThings(Crawler $dom, string $formName, array $inputs, array $expectedValues = []): void
    {
        $form = $dom->filterXPath("//form[@name='{$formName}']")->form();
        foreach ($expectedValues as $expectedValueKey => $expectedValue) {
            $this->assertEquals($expectedValue, $form->get($expectedValueKey));
        }
        $form->setValues($inputs);
        $this->client->submit($form);
    }
}
