<?php

namespace App\Tests\Application;

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\BrowserKit\AbstractBrowser;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class ApplicationTestCase extends WebTestCase
{
    protected readonly AbstractBrowser $client;
    protected readonly UrlGeneratorInterface $router;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = self::createClient();
        $this->router = $this->getContainer()->get(UrlGeneratorInterface::class);
    }
}
