name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: ./bin/install

      - name: Run Pint
        run: ./vendor/bin/sail bin pint

      - name: Format Frontend
        run: ./vendor/bin/sail npm run format:check
        if: always()

      - name: Lint Frontend
        run: ./vendor/bin/sail npm run lint
        if: always()

      - name: Tests
        run: ./vendor/bin/sail artisan test --parallel --coverage
        if: always()

      - name: Tests
        run: ./vendor/bin/sail dusk
        if: always()
