name: tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Copy env
        run: cp .env.example .env

      - name: Composer install
        run: composer install --ignore-platform-reqs

      - name: Sail up
        run: ./vendor/bin/sail up --build --detach

      - name: Keygen
        run: ./vendor/bin/sail artisan key:generate

      - name: Clear cache
        run: ./vendor/bin/sail artisan optimize

      - name: Migrate
        run: ./vendor/bin/sail artisan migrate:fresh --seed

      - name: NPM Install
        run: ./vendor/bin/sail npm i

      - name: NPM Build
        run: ./vendor/bin/sail npm run build

      - name: Run CI Checks
        run: ./vendor/bin/sail composer ci:check
