name: tests

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read

jobs:
    ci:
        continue-on-error: true
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
                with:
                    persist-credentials: false

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.5'

            -   name: Cache NPM
                id: cache-npm
                uses: actions/cache@v6
                with:
                    path: ./node_modules
                    key: npm-${{ hashFiles('package-lock.json') }}

            -   name: Cache Composer
                id: cache-composer
                uses: actions/cache@v6
                with:
                    path: ./vendor
                    key: composer-${{ hashFiles('composer.lock') }}

            -   name: Copy env
                run: cp .env.example .env

            -   name: Composer install
                run: composer install --ignore-platform-reqs

            -   name: Sail up
                run: ./vendor/bin/sail up --detach --wait

            -   name: Composer reinstall
                run: ./vendor/bin/sail composer i

            -   name: Keygen
                run: ./vendor/bin/sail artisan key:generate

            -   name: Clear cache
                run: ./vendor/bin/sail artisan optimize

            -   name: Migrate
                run: ./vendor/bin/sail artisan migrate:fresh --seed -vvv --no-interaction

            -   name: NPM Install
                run: ./vendor/bin/sail npm i

            -   name: NPM Build
                run: ./vendor/bin/sail npm run build

            -   name: Run CI Checks
                if: always()
                run: ./vendor/bin/sail npm run check

            -   name: Run CI Checks
                if: always()
                run: ./vendor/bin/sail npm run types:check

            -   name: Run CI Checks
                if: always()
                run: ./vendor/bin/sail composer lint:check

            -   name: Run CI Checks
                if: always()
                run: ./vendor/bin/sail composer types:check

            -   name: Run CI Checks
                if: always()
                run: ./vendor/bin/sail artisan test

