name: tests

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read

jobs:
    ci:
        continue-on-error: true
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
                with:
                    persist-credentials: false

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.5'

            -   name: Cache Docker images
                id: cache-docker
                uses: actions/cache@v6
                with:
                    path: ./docker-images.tar
                    key: docker-${{ runner.os }}-${{ hashFiles('compose.yaml') }}

            -   name: Load docker images
                if: steps.cache-docker.outputs.cache-hit == 'true'
                run: docker load -i ./docker-images.tar

            -   name: Cache NPM
                id: cache-npm
                uses: actions/cache@v6
                with:
                    path: prime-numbers
                    key: npm-${{ hashFiles('package-lock.json') }}

            -   name: Cache Composer
                id: cache-composer
                uses: actions/cache@v6
                with:
                    path: ./vendor
                    key: composer-${{ hashFiles('composer.lock') }}

            -   name: Copy env
                run: cp .env.example .env

            -   name: Composer install
                run: composer install --ignore-platform-reqs

            -   name: Sail up
                run: ./vendor/bin/sail up --detach --wait

            -   name: Save Docker images
                if: steps.cache-docker.outputs.cache-hit != 'true'
                run: docker save $(docker images -q) -o ./docker-images.tar

            -   name: Keygen
                run: ./vendor/bin/sail artisan key:generate

            -   name: Clear cache
                run: ./vendor/bin/sail artisan optimize

            -   name: Migrate
                run: ./vendor/bin/sail artisan migrate:fresh --seed -vvv --no-interaction

            -   name: NPM Install
                run: ./vendor/bin/sail npm i

            -   name: NPM Build
                run: ./vendor/bin/sail npm run build

            -   name: Run CI Checks
                run: ./vendor/bin/sail composer ci:check

